name: validate core and above

on: 
  push:
    branches: [ core ]
    paths: [ "**/*.cs" ] 
  pull_request:
    branches: [ main, dev, core ]
    paths: [ "**/*.cs" ]

jobs:
  csharpier:
    runs-on: ubuntu-latest
    name: format
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "9.0.x"
      - run: dotnet tool restore
      - run: dotnet csharpier format .

  unity_runner:
    runs-on: ubuntu-latest
    name: unity test runner

    steps:
      - name: checkout code 
        uses: actions/checkout@v6

      - name: run playmode tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 6000.0.60f1
          testMode: PlayMode
          githubToken: ${{ secrets.GITHUB_TOKEN }}  
